FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-base.txt requirements-api.txt requirements-ml.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=1000 -r requirements-api.txt -r requirements-ml.txt

COPY . /app

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]