apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-pvc
  labels:
    app: ecommerce-api
    component: artifacts-storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3   # or your cluster’s default
